# Site settings
title: "CS423: Networks"
email: cs423.nuig@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Network Science is the study of network representations of physical, 
  biological, and social phenomena.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cs423.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  cs423
disqus: cs423
google_analytics: UA-72475442-1

# permalinks
permalink: "notes/:year/:month/:day/:title.html"

# Build settings
markdown: kramdown
future: true

# Additional gems
gems:
  - jekyll-sitemap
  
# Default values
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      author: "Götz Pfeiffer"
      layout: post
      category: notes
